server:
  port: 8080

spring:
  datasource:
    username: root
    password: aa6638360
    url: jdbc:mysql://localhost:3306/springboottest?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  # spring整合email配置
  mail:
    host: smtp.qq.com
    username: 1289563709@qq.com
    password: dyllkbtpfnthjfbb

  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最小空闲连接
        max-idle: 10
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 50
    # 默认是索引为0的数据库
    database: 0

#swagger启用开关(开发、测试环境可以开启，正式环境不开启，避免暴露接口)
swagger:
  enable: true