spring:
  profiles:
    active: test
    #连接池配置_1
    druid:
      url: jdbc:mysql://localhost:3306/springboottest?characterEncoding=UTF-8@&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
      username: druid
      password: aa6638360
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 1
      max-active: 100
      test-on-borrow: true

    #    #连接池配置_2
    #    datasource:
    #      driver-class-name: com.mysql.jdbc.Driver
    #      # 使用druid数据源
    #      type: com.alibaba.druid.pool.DruidDataSource
    #      druid:
    #        # 配置测试查询语句
    #        validationQuery: SELECT 1 FROM DUAL
    #        # 初始化大小，最小，最大
    #        initialSize: 10
    #        minIdle: 10
    #        maxActive: 200
    #        # 配置一个连接在池中最小生存的时间，单位是毫秒
    #        minEvictableIdleTimeMillis: 180000
    #        testOnBorrow: false
    #        testWhileIdle: true
    #        removeAbandoned: true
    #        removeAbandonedTimeout: 1800
    #        logAbandoned: true
    #        # 打开PSCache，并且指定每个连接上PSCache的大小
    #        poolPreparedStatements: true
    #        maxOpenPreparedStatements: 100
    #        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #        filters: stat,wall,log4j
    #        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    #        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #main:
    #当遇到同样名字的时候，是否允许覆盖注册
    #allow-bean-definition-overriding: true

logging:
  config: classpath:log4j2.yml
